name: superman_vapeshop
description: "A simple POS system for SUPERMAN Vapeshop"

# Prevent accidental publishing to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # State Management
  provider: ^6.1.1

  # UI Components
  cupertino_icons: ^1.0.2
  intl: ^0.18.1 # For date/number formatting
  fl_chart: ^0.66.0 # For sales charts/reports

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  
  # Linting
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Uncomment if you plan to use assets (e.g., images, icons)
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # Uncomment if you need custom fonts
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700